# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Set up build environment
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
    - run: pip install -r requirements.txt
      # https://stackoverflow.com/a/71042698/358804
      shell: bash
