# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Set up build environment
description: Installs dependencies
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
    - name: Install packages
      run: uv sync --locked
      # https://stackoverflow.com/a/71042698/358804
      shell: bash
