# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Set up build environment
runs:
  using: composite
  steps:
    - name: Install Conda packages
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: extras/environment.yml
        init-shell: bash
        cache-downloads: true
        cache-environment: true
