# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id2
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  jobs:
    # https://jupyterbook.org/en/stable/publish/readthedocs.html
    pre_build:
      - jupyter-book config sphinx .
    post_build:
      - make fix_double_escaping build_dir="$READTHEDOCS_OUTPUT"

sphinx:
  # https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
  configuration: conf.py

conda:
  environment: extras/docs/environment.yml
