# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id2
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  # https://jupyterbook.org/en/stable/publish/readthedocs.html
  jobs:
    pre_build:
      - jupyter-book config sphinx .

conda:
  environment: extras/docs/environment.yml
