# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = [
    "--ignore=extras/autograder/",
]

[tool.ruff]
extend-exclude = ["final_project/*.ipynb"]
