#!/bin/bash

set -e
set -x


# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#updating-an-environment
mamba env update --file extras/environment.yml --prune

LOCK_FILE=extras/environment.lock.yml
echo "# generated by $0" > $LOCK_FILE
# https://stackoverflow.com/a/41274348/358804
mamba env export -n python-public-policy | grep -v "^prefix: " >> $LOCK_FILE

./extras/scripts/update_lectures.sh

echo "Please update homework notebooks separately, in python-public-policy-assignments"
