#!/bin/bash

set -e
set -x


# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#updating-an-environment
mamba env update --file extras/environment.yml --prune

echo "# generated by $0" > extras/environment.lock.yml
# https://stackoverflow.com/a/41274348/358804
mamba env export | grep -v "^prefix: " >> extras/environment.lock.yml

./extras/scripts/update_all.sh
