name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  ## local development ##
  - notebook=7.*
  - ruff
  - pip
  - pip:
      - gradescope_utils

  # extensions
  - jupyter-resource-usage
  - nb_conda_kernels

  ## packages imported directly in notebooks ##
  # match version in Colab returned by `!python --version`
  - python=3.12.11
  # match versions in Colab returned by `!pip list`
  # required for pandas' read_html()
  - html5lib=1.1
  - lxml
  - pandas=2.2.2
  # Using v6 (newer than Colab) to avoid the need for the plugin in the base environment. Using (unreleased) v6.0.1 to avoid a bug in the HTML export.
  # https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#301----2025-02-18
  - plotly>=6.0.1
  - requests=2.32.4
  # https://github.com/statsmodels/statsmodels/releases/tag/v0.14.5
  - statsmodels>=0.14.5
  - scipy
  ## supporting packages for notebooks ##
  # makes kernel available in JupyterHub
  - ipykernel
  - unzip
  - wget
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # required for plotly rendering
  # https://github.com/plotly/plotly.py/blob/v6.0.0/packages/python/plotly/plotly/io/_renderers.py#L426
  - nbformat>=4.2.0
  # needed for plotly
  # https://plotly.com/python/getting-started/#jupyterlab-support
  - anywidget
  - isoduration
  - narwhals
  # for AI magic in JupyterHub
  # - pip
  # - pip:
  #     # https://python.langchain.com/docs/versions/v0_3/#1-do-not-use-the-langchain_corepydantic_v1-namespace
  #     - langchain-core==0.2.*
  #     - langchain-openai
  #     # path/filename may need to be adjusted
  #     # - ../../rit_jupyter_ai_magics-2.21.0-py3-none-any.whl

  ## CI ##
  - jinja2
  # https://github.com/jupyter/nbconvert/pull/2196
  - nbconvert>=7.16.6
  - nbdime
  - pytest

  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=1.0.4.post1
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - sphinx>=6.2.0
